import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Detox Blueprint",
  description: "Generated by rudy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "min-w-screen flex min-h-screen flex-col items-center justify-between bg-[#1953aa] text-white"}>{children}</body>
    </html>
  );
}
